# Generated by Django 4.0.5 on 2022-06-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uid',
            new_name='uuid',
        ),
    ]
